version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=testing
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mytestdb
  # APP*****************************************
  springbootapp:
    restart: always
    build: ./backend/srpingwebapp
    container_name: springbootapp
    ports:
      - 8080:8080
    depends_on:
      - postgres
    links:
      - postgres
volumes:
  postgres-data:
